//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Middleware.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Middleware.Models")]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppVersionField;
        
        private object DataField;
        
        private string InfoField;
        
        private string OperationNameField;
        
        private string OperationVersionField;
        
        private bool StatusOpField;
        
        private string TokenAppField;
        
        private string TokenUserField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AppVersion
        {
            get
            {
                return this.AppVersionField;
            }
            set
            {
                this.AppVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OperationName
        {
            get
            {
                return this.OperationNameField;
            }
            set
            {
                this.OperationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OperationVersion
        {
            get
            {
                return this.OperationVersionField;
            }
            set
            {
                this.OperationVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool StatusOp
        {
            get
            {
                return this.StatusOpField;
            }
            set
            {
                this.StatusOpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TokenApp
        {
            get
            {
                return this.TokenAppField;
            }
            set
            {
                this.TokenAppField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TokenUser
        {
            get
            {
                return this.TokenUserField;
            }
            set
            {
                this.TokenUserField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEndpoint", CallbackContract=typeof(IEndpointCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IEndpoint
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEndpoint/MService")]
    void MService(Middleware.Models.Message message);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEndpoint/MService")]
    System.Threading.Tasks.Task MServiceAsync(Middleware.Models.Message message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEndpointCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEndpoint/MServiceCallback")]
    void MServiceCallback(Middleware.Models.Message message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEndpointChannel : IEndpoint, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EndpointClient : System.ServiceModel.DuplexClientBase<IEndpoint>, IEndpoint
{
    
    public EndpointClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public EndpointClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public EndpointClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public EndpointClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public EndpointClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void MService(Middleware.Models.Message message)
    {
        base.Channel.MService(message);
    }
    
    public System.Threading.Tasks.Task MServiceAsync(Middleware.Models.Message message)
    {
        return base.Channel.MServiceAsync(message);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRestAPI")]
public interface IRestAPI
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestAPI/MServiceRest", ReplyAction="http://tempuri.org/IRestAPI/MServiceRestResponse")]
    void MServiceRest(Middleware.Models.Message message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestAPI/MServiceRest", ReplyAction="http://tempuri.org/IRestAPI/MServiceRestResponse")]
    System.Threading.Tasks.Task MServiceRestAsync(Middleware.Models.Message message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRestAPIChannel : IRestAPI, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RestAPIClient : System.ServiceModel.ClientBase<IRestAPI>, IRestAPI
{
    
    public RestAPIClient()
    {
    }
    
    public RestAPIClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RestAPIClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void MServiceRest(Middleware.Models.Message message)
    {
        base.Channel.MServiceRest(message);
    }
    
    public System.Threading.Tasks.Task MServiceRestAsync(Middleware.Models.Message message)
    {
        return base.Channel.MServiceRestAsync(message);
    }
}
